# Generated by Django 6.1.1 on 2026-10-02 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('websites', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True))),
                ('is_active', models.BooleanField()),
                ('country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"label"."artist"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_number', models.TextField()),
                ('name', models.TextField()),
                ('released_at', models.DateTimeField()),
                ('headline', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_image')),
                ('website_image', models.ImageField(blank=True, null=True, upload_to='website_image')),
                ('download_link', models.TextField(blank=True, null=True)),
                ('download_link_lossless', models.TextField(blank=True, null=True)),
                ('mentions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"label"."release"',
                'ordering': ['-released_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"label"."release_artists"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"label"."release_tags"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': '"label"."tag"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('pos', models.IntegerField()),
                ('duration', models.TimeField()),
                ('track_mp3', models.FileField(blank=True, null=True, upload_to='track_mp3')),
            ],
            options={
                'db_table': '"label"."track"',
                'managed': False,
            },
        ),
    ]
